// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectPartB.Areas.Identity.Data;

#nullable disable

namespace ProjectPartB.Migrations
{
    [DbContext(typeof(CustomIdentityContext))]
    [Migration("20231028064849_SeedingUserRoles")]
    partial class SeedingUserRoles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "5555b661-884c-4d64-8a2d-868082a6233a",
                            ConcurrencyStamp = "c27689ac-f37b-4f5b-9412-e4862879ad9c",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "e22f5b2e-e518-45c3-8c11-387bffe556b7",
                            ConcurrencyStamp = "be39c68b-a9b4-4b1b-bb2f-04a62c67b96e",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "f81b3e8e-92a0-4e3a-96c1-ee015d601f54",
                            ConcurrencyStamp = "ff7fa5fe-34cc-4cce-bd20-7f49ea36ed95",
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = "604f7419-6b49-4505-8afa-b663267dba8b",
                            ConcurrencyStamp = "14380418-857f-4d71-8ccb-a04594ebbcf2",
                            Name = "Visitor",
                            NormalizedName = "VISITOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "d1c63891-7137-491b-953e-b85ca823ab51",
                            RoleId = "5555b661-884c-4d64-8a2d-868082a6233a"
                        },
                        new
                        {
                            UserId = "b082c99a-d37c-4e2b-8fc4-f792fbc5afdb",
                            RoleId = "e22f5b2e-e518-45c3-8c11-387bffe556b7"
                        },
                        new
                        {
                            UserId = "0e2fd500-ff58-4848-992b-62dcaae9c021",
                            RoleId = "f81b3e8e-92a0-4e3a-96c1-ee015d601f54"
                        },
                        new
                        {
                            UserId = "d4274cf7-e7ff-4b53-b7c5-6850560a0a38",
                            RoleId = "604f7419-6b49-4505-8afa-b663267dba8b"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectPartB.Areas.Identity.Data.WebUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrivingLicense")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d1c63891-7137-491b-953e-b85ca823ab51",
                            AccessFailedCount = 0,
                            Address = "admin",
                            ConcurrencyStamp = "08460e86-28b3-4afa-a229-dfb0fb44d09c",
                            DrivingLicense = "fads213",
                            Email = "administrator@example.com",
                            EmailConfirmed = true,
                            FullName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMINISTRATOR@EXAMPLE.COM",
                            NormalizedUserName = "ADMINISTRATOR@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBbOeXe6OBteru5r445J/qZ/D/w3jDmpHST8oaRvnB8zCydo2CMY5wuc4mVQZ7T9Gg==",
                            Phone = "0210888888",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9644061b-d51a-4fa8-b3b9-6b449dcee3cd",
                            TwoFactorEnabled = false,
                            UserID = "1",
                            UserName = "administrator@example.com"
                        },
                        new
                        {
                            Id = "b082c99a-d37c-4e2b-8fc4-f792fbc5afdb",
                            AccessFailedCount = 0,
                            Address = "manager",
                            ConcurrencyStamp = "97328f73-767c-4fb0-9eac-3418ccb813d9",
                            DrivingLicense = "fads213",
                            Email = "manager@example.com",
                            EmailConfirmed = true,
                            FullName = "manager",
                            LockoutEnabled = false,
                            NormalizedEmail = "MANAGER@EXAMPLE.COM",
                            NormalizedUserName = "MANAGER@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBrSfueNDvlOsH2/IkpEJ/byZLvE9+z8B/HzJ0T//eiPcCMwL4SZUYGB81G/wFOtMA==",
                            Phone = "0210888888",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b4063eea-b3a4-40ff-acb9-28b6a983755a",
                            TwoFactorEnabled = false,
                            UserID = "2",
                            UserName = "manager@example.com"
                        },
                        new
                        {
                            Id = "0e2fd500-ff58-4848-992b-62dcaae9c021",
                            AccessFailedCount = 0,
                            Address = "editor",
                            ConcurrencyStamp = "b4a6bfcc-5809-4768-b368-2c4699de4251",
                            DrivingLicense = "fads213",
                            Email = "editor@example.com",
                            EmailConfirmed = true,
                            FullName = "editor",
                            LockoutEnabled = false,
                            NormalizedEmail = "EDITOR@EXAMPLE.COM",
                            NormalizedUserName = "EDITOR@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDg19IM5m88wJbeuNIhOFVs5UqYB7orOl6HFAem15WD0UxmSacx1ojsZ296GTho+tA==",
                            Phone = "0210888888",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bf990da8-53fa-4593-93fa-a14381ad33df",
                            TwoFactorEnabled = false,
                            UserID = "3",
                            UserName = "editor@example.com"
                        },
                        new
                        {
                            Id = "d4274cf7-e7ff-4b53-b7c5-6850560a0a38",
                            AccessFailedCount = 0,
                            Address = "visitor",
                            ConcurrencyStamp = "c7488722-a0c5-4c84-8d8e-4402ca1ba6f6",
                            DrivingLicense = "fads213",
                            Email = "visitor@example.com",
                            EmailConfirmed = true,
                            FullName = "visitor",
                            LockoutEnabled = false,
                            NormalizedEmail = "VISITOR@EXAMPLE.COM",
                            NormalizedUserName = "VISITOR@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPMax3yrvHl3L4DL0sPT6mum1r127VvZ4pjMv4m6Kaj0ENXYQAXBikE6Z/tBqqKIRw==",
                            Phone = "0210888888",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3aac373c-86d6-4a94-98d0-c27418c592e1",
                            TwoFactorEnabled = false,
                            UserID = "4",
                            UserName = "visitor@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProjectPartB.Areas.Identity.Data.WebUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProjectPartB.Areas.Identity.Data.WebUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectPartB.Areas.Identity.Data.WebUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProjectPartB.Areas.Identity.Data.WebUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
